services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["gunicorn", "shop_analytics.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./source:/app/source
      - static_volume:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: postgres:16
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'"]
      interval: 5s
      retries: 3
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  static_volume:
  postgres_data: