# Generated by Django 5.2.3 on 2025-06-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="apply_vat",
            field=models.BooleanField(default=False, verbose_name="Apply 12% VAT"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Delivery Cost",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                verbose_name="Product Discount Percentage",
            ),
        ),
    ]
